### ISSUE TITLE
Changes to UIMS broke the api

### ISSUE THREAD

**Issue by mokshchaudhary** [cu-unofficial/uims-api#15]
The way CUIMS fetch the attendance has changed breaking the api 
`Traceback (most recent call last):
  File "q.py", line 7, in <module>
    subjects = my_account.attendance
  File "/home/moksh/Desktop/uims-api/uims_api/session.py", line 79, in attendance
    self._attendance = self._get_attendance()
  File "/home/moksh/Desktop/uims-api/uims_api/session.py", line 114, in _get_attendance
    raise UIMSInternalError('UIMS internal error occured')
uims_api.exceptions.UIMSInternalError: UIMS internal error occured`

**Comment by xpt1x** [comment]
This is fixed with a workaround on another project https://github.com/xpt1x/PocketIMS/blob/master/uims_api/session.py
I will update here soon :)

**Comment by mokshchaudhary** [comment]
Seems it's working 
Great Job !
Btw feel free to ping me if you're interested in making a flutter app for the api :+1:

**Comment by xpt1x** [comment]
Fixed in https://github.com/cu-unofficial/uims-api/pull/16

@mokshchaudhary actually i am already working on a React Native implementation with some peers, its currently closed source for a while but we will open source it soon, then your contributions are welcome!

And thanks for raising this issue, we need folks like you to keep this project alive :smile:

**Comment by mokshchaudhary** [comment]
Sure 👍👍
